/**
 * Export guests to CSV file
 * @param {Array} guests - Array of guest objects
 * @param {string} filename - Name of the CSV file
 */
export const exportToCSV = (guests, filename = 'volutrack-guests.csv') => {
  // Create CSV header
  const headers = ['Name', 'Status', 'Confirmed'];

  // Create CSV rows
  const rows = guests.map(guest => [
    guest.name,
    guest.isConfirmed ? 'Confirmed' : 'Pending',
    guest.isConfirmed ? 'Yes' : 'No'
  ]);

  // Combine header and rows
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');

  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');

  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

/**
 * Get printable HTML for guest list
 * @param {Array} guests - Array of guest objects
 * @param {Object} stats - Statistics object with attending, unconfirmed, total
 * @returns {string} HTML string for printing
 */
export const getPrintableHTML = (guests, stats) => {
  const date = new Date().toLocaleDateString();

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Volutrack - Guest List</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #333; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .stats { margin: 20px 0; padding: 15px; background: #f5f5f5; border-radius: 8px; }
        .stats-row { display: flex; justify-content: space-between; margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #58b7cd; color: white; }
        .confirmed { color: #2e7d32; font-weight: bold; }
        .pending { color: #d32f2f; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #666; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Volutrack - Guest List</h1>
        <p>Rosamond Elementary - ${date}</p>
      </div>

      <div class="stats">
        <div class="stats-row">
          <strong>Attending:</strong>
          <span>${stats.attending}</span>
        </div>
        <div class="stats-row">
          <strong>Unconfirmed:</strong>
          <span>${stats.unconfirmed}</span>
        </div>
        <div class="stats-row">
          <strong>Total:</strong>
          <span>${stats.total}</span>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${guests.map((guest, index) => `
            <tr>
              <td>${index + 1}</td>
              <td>${guest.name}</td>
              <td class="${guest.isConfirmed ? 'confirmed' : 'pending'}">
                ${guest.isConfirmed ? 'Confirmed' : 'Pending'}
              </td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="footer">
        <p>Generated by Volutrack - ${date}</p>
      </div>
    </body>
    </html>
  `;
};

/**
 * Print guest list
 * @param {Array} guests - Array of guest objects
 * @param {Object} stats - Statistics object
 */
export const printGuestList = (guests, stats) => {
  const printWindow = window.open('', '_blank');
  printWindow.document.write(getPrintableHTML(guests, stats));
  printWindow.document.close();
  printWindow.focus();

  // Small delay to ensure content is loaded before printing
  setTimeout(() => {
    printWindow.print();
  }, 250);
};
